### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by partofthething** [EronHennessey/sphinx-mobi-builder#2]
This isn't yet python3 compatible with some exception syntax and whatnot. 

I actually ran 2to3 on it and rebuilt with python3 and it seems to at least start running. I haven't been able to fully test it because of another issue.

**Comment by EronHennessey** [comment]
I've been considering this issue and dove into solving it today. However:

* See [this part](https://github.com/EronHennessey/sphinx-mobi-builder/blob/master/README.rst#important-why-you-dont-want-to-use-this) of the README, which I've just updated. The Sphinx docs already pointed to a better way of generating `.mobi` files.
* I think that this builder would be better overall if based on the Epub builder, but it would run `kindlegen` automatically.  It's got other issues too (it ought to be `sphinxcontrib.builders.mobi`, its `setup.py` is pretty out of date, and so on).
